### ISSUE TITLE
Setup Knowledge Areas Feature

### ISSUE THREAD

**Issue by baesparza** [UTPL-Rank/UTPL-Rank-Web#14]
- [x] Create Knowledge Areas Feature Module `KnowledgeAreasModule` and routing module `KnowledgeAreaRoutingModule`.
- [x] Link this feature module to the dashboard routing module with the base url `/areas-conocimiento`

**Comment by jpablopachar** [comment]
The KnowledgeAreasModule and KnowledgeAreasRoutingModule have been previously created.

**Comment by baesparza** [comment]
The tasks of this issue have been moved to #7
